apiVersion: app:1.0-41
kind: Deployment
metadata:
  name: register-app:1.0-41
spec:
  replicas: 2
  selector:
    matchLabels:
      app:1.0-41
  template:
    metadata:
      labels:
        app:1.0-41
    spec:
      containers:
        - name: register-app:1.0-41
          image: murulii/app:1.0-41
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
